export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVED_INGREDIENTS = "REMOVED_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED="FETCH_INGREDIENTS_FAILED";
// export const TOTAL_PRICE = "TOTAL_PRICE";